name: VillagerInventory
version: ${project.version}
main: ca.henrychang.villagerinventory.VillagerInventory
api-version: 1.19
authors: [ hdlineage ]
description: Allows players to interact with villager inventory
website: henrychang.ca
